### ISSUE TITLE
Data Schema and Database Setup

### ISSUE THREAD

**Issue by stanleykaris** [trapper99/CloudmyTribe-projects#2]
# Task 1: Defining the table schema
- [ ] Identifying the required fields.
- [ ] Set the primary key and indexes.
- [ ] Creating the JSON Data Structure

# Task 2: Loading sample data:
- [ ] Using AWS CLI or using AWS Console.

# Task 3: Creating IAM policies:
- [ ] Attaching the `AmazonDynamoDBFullAccess` policy.
