### ISSUE TITLE
Lambda Function Development

### ISSUE THREAD

**Issue by stanleykaris** [trapper99/CloudmyTribe-projects#4]
# Task 1: Creating Lambda Function for CRUD Operations
- [ ] Setting up a new Lambda function in the AWS Console.
- [ ] Write code to handle Create, Read, Update, and Delete operations.

# Task 2: Test Lambda functions locally
- [ ] Use AWS SAM or other tools to test Lambda functions locally.

# Task 3: Deploy Lambda Functions
- [ ] Deploying to AWS
- [ ] Test them using the management console
