### ISSUE TITLE
Setting up a CI/CD pipeline using Github Actions

### ISSUE THREAD

**Issue by stanleykaris** [trapper99/CloudmyTribe-projects#6]
# Task: Setting Github Actions Workflow
- [ ] Write a workflow `yaml` file that defines the CI/CD pipeline
- [ ] Storing environment variables and secrets to the repository settings.
- [ ] Test the workflow.
- [ ] Verify the actions execute as expected and troubleshoot any issues that arise.
